version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # Use one of the supported Python versions available in your build environment
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y unzip
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt-get update && apt-get install -y terraform
  build:
    commands:
      - terraform init
      - terraform plan -out=tfplan

